### ISSUE TITLE
ABM missing from Enigma2 plugin feed

### ISSUE THREAD

**Issue by p17blo** [oe-alliance/AutoBouquetsMaker#1]
Probably wrong place to ask,but ABM is currently missing from the enigma2 plugin feed - Who and how would get that back in the feed?

**Comment by AbuBaniaz** [comment]
Probably resolved by this.

https://github.com/oe-alliance/oe-alliance-core/commit/25a07c6c6123ea4cd8ed5f2d2cc4c05e080b91db

**Comment by educare1** [comment]
i can still not download it on my zgemma hs. it does not show up on the feeds. please help really need it

**Comment by AbuBaniaz** [comment]
Ensure you are on latets version of your image, If you still cannot find/install the plugin, please start a support thread on your image forum.
