### ISSUE TITLE
28.2 sky uk channels wrong after may 1 update

### ISSUE THREAD

**Issue by chenks** [oe-alliance/AutoBouquetsMaker#75]
channel ordering is wrong for regions after the may 1 sky uk 28.2 config update.
scotland west custom doesn't have BB1 Scot HD at 101, or BBC2 HD at 102, or Channel4 HD at 104.
115 is missing completely, which should be BBC 2 Scotland SD
141 should be BBC Alba , but BBC Two HD is on 141, which should be on 102.

i assume there will be other channels wrong in other regions, but i only know about Scotland West custom.

**Comment by nicbedford** [comment]
I have a similar issue (bot sure if it's the same)

I used to have it set to create FTA HD bouquet, which would create channels 1 - x, and then sky bouquets at 100, 200, etc...
I am using region custom
I also have swap HD/SD.

Since the changes for May 1st, I'm not getting some of the FTA HD channels, e.g. ITV HD, it's not populating 803, or 103, or 3. Channel 4 HD, it's not populating 804, 104 or 4.

**Comment by AbuBaniaz** [comment]
This should be fixed now.

**Comment by AbuBaniaz** [comment]
We will have this issue while we have the four nations all on one file.

**Comment by chenks** [comment]
is it something that is likely to be resolved in the future?

**Comment by chenks** [comment]
yes i know that.
so is there a potential solution?

**Comment by AbuBaniaz** [comment]
Fixed here

https://github.com/oe-alliance/AutoBouquetsMaker/commit/af40b1c80254b05a69f1de8187003392dd2851ac

**Comment by chenks** [comment]
i assume this is fixed in the ABM3.0 release (along with the updated XML file) ?
is ABM3.0 compatible with OATV6.0? as i have manually installed ABM3.0 and it doesn't show up in Service Searching after a reboot (on enigma2 device).

**Comment by chenks** [comment]
sorry guys, but this is not fixed.
just updated to ABM 3.0 and the new XML and it worse than what it was before.

i no longer have STV HD on 103 (previously i did)

**Comment by davesayers2014** [comment]
Aee attached, probably not perfect but seems to work 
[sat_282_sky_uk_STV.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/2044888/sat_282_sky_uk_STV.zip)

**Comment by davesayers2014** [comment]
Regarding the conditional swaps are all needed?

Unless the python code has changed swap will only work if there is an HD channel in that position.

Couldn't we have the ITV/STV swaps how they was?

`<channel number="103" with="803"/>  		
 <channel number="103" with="176"/> `

Because East Midlands is missing the swap to.

I think we only had the regional issues with BBC 1 HD and BBC 2 HD on 115

**Comment by Huevos** [comment]
The idea is to be able to swap without interfering with the provider's LCNs for the region. The thing is there are are a lot of regions and there are going to be minor teething problems on some regions. But at least now we have a system we can control. Please post any problems or suggestions here: https://www.world-of-satellite.com/showthread.php?59570-HD-swap-discussion&p=470913#post470913
